### PR TITLE
eslint: imports should come before other code

### PR DESCRIPTION
**Pull request by go-oleg**
cc @rlgomes @mnibecker

### CODE REVIEW

**Comment by go-oleg** [comment]
They are hoisted and always run before any preceding code which leads to confusing behavior if there _is_ preceding code.

**Comment by rlgomes** [comment]
noice! if we start using imports in other repos we should probably make sure this is enforced the same way to save us heaches.

**Comment by mnibecker** [comment]
Wait, doesn't this go against the spec for how imports will eventually work? Feels like a hack...

**Comment by go-oleg** [comment]
No it doesn't, it makes it so that your code matches the order of execution that the spec defines (i.e. imports go first). Its the same as having an eslint rule that all `var`s should be [declared at the top](http://eslint.org/docs/rules/vars-on-top.html).

**Comment by mnibecker** [comment]
oooh, sry man this is an eslint rule. I thought you were messing with babel, my bad. good stuff.

**Comment by go-oleg** [comment]
no worries!

**Pull request merged**
